### ISSUE TITLE
rm -rf .git not working on PowerShell 7.2.1

### ISSUE THREAD

**Issue by pjonatansr** [Suares01/App_Node_Template#1]
Hi, I was trying to remove .git on PowerShell 7.2.1 with the README instructions, but the follow code wasn't working for me:
```shellscript
$ rm -rf .git
```
So I used this code instead: 

```shellscript
$ rm -r -fo .git
```
Feel free if you want to add to the README.

By the way, thank you for the template.

**Comment by Suares01** [comment]
Hi, thanks for sharing this! I'll add it to the README. And you're welcome for the template, if you have any ideas to improve feel free to share.
